@include('layouts.private.admintemplate.header')
@include('layouts.private.admintemplate.sidebar')
@include('layouts.private.admintemplate.navbar')
@yield('content')
@include('layouts.private.admintemplate.footer')
@include('layouts.private.admintemplate.js')
